### ISSUE TITLE
Document design decisions

### ISSUE THREAD

**Issue by koppor** [jbibtex/jbibtex#20]
I am a fan of recording [Lightweight Architecture Decision Records](https://www.thoughtworks.com/radar/techniques/lightweight-architecture-decision-records) and recommend the format [MADR](https://adr.github.io/madr/) for it.

When using jbibtex 1.0.17, [we found out](https://github.com/JabRef/cloudref/commit/c507b98118348528169467a133a7c356d978a7d5) that `@class` is used to indicate the type of a field in jbibtex.

Than means the JSON is

    publisher: {
         string: '',
         '@class': 'org.jbibtex.StringValue',
         style: 'BRACED',
      }

instead of

    publisher: {
         string: '',
         'type': 'org.jbibtex.StringValue',
         style: 'BRACED',
      }

Is this intended?

**Comment by vruusmann** [comment]
I'm fairly ignorant about JSON and its conventions. Using `@class` for type information was Jackson's default, so I thought it's reasonable. What's the reason to prefer `type`?

**Comment by koppor** [comment]
I see. It is uncommon in JSON to have at signs in the name. `type` reads more natural than `@class`. You know, the human-readable argumentation we had at XML is now also used at JSON 🎉

**Comment by vruusmann** [comment]
> It is uncommon in JSON to have at signs in the name. type reads more natural than @class

But maybe the point of an "unnatural" starting character is to demonstrate that this is a machine-generated attribute, which should not be shown to humans/be manipulated by them?

What do you suggest, changing `@class` to `type` in JBibTeX version 1.0.18?

**Comment by koppor** [comment]
Either keep it (because the content is `java.lang.String`, which is really java-specific) or change it to `type = {String}`. Because the latter is hard to implement and we are currently not optimizing for a human-readable JSON, leave everything as is.

In case I have time, I'll create a MADR file and provide a PR.


Side thing:

The `BibTeXEntry` takes

    '@class': 'org.jbibtex.BibTeXEntry'

This was not necessary in the self-made implementation. Can this line just be removed?
