### ISSUE TITLE
Using a dot character as entry identifier

### ISSUE THREAD

**Issue by playmaker9511** [jbibtex/jbibtex#24]
Hi There,

i desperately try to parse an entry. But i just get TokenException.

This Entry i try to parse: 
@book{.,
 title = {Conference: Security and Privacy in Spontaneous Interaction and Mobile Phone Use, 4th International Workshop on, At Newcastle, UK}
}

org.jbibtex.TokenMgrException: Lexical error at line 3, column 7.  Encountered: "." (46), after : ""
	at org.jbibtex.BibTeXParserTokenManager.getNextToken(BibTeXParserTokenManager.java:719) ~[jbibtex-1.0.18.jar:na]
	at org.jbibtex.BibTeXParser.jj_scan_token(BibTeXParser.java:1045) ~[jbibtex-1.0.18.jar:na]
	at org.jbibtex.BibTeXParser.jj_3R_4(BibTeXParser.java:854) ~[jbibtex-1.0.18.jar:na]
	at org.jbibtex.BibTeXParser.jj_3R_3(BibTeXParser.java:915) ~[jbibtex-1.0.18.jar:na]
	at org.jbibtex.BibTeXParser.jj_3_7(BibTeXParser.java:844) ~[jbibtex-1.0.18.jar:na]
	at org.jbibtex.BibTeXParser.jj_2_7(BibTeXParser.java:821) ~[jbibtex-1.0.18.jar:na]
	at org.jbibtex.BibTeXParser.Entry(BibTeXParser.java:454) ~[jbibtex-1.0.18.jar:na]
	at org.jbibtex.BibTeXParser.Object(BibTeXParser.java:293) ~[jbibtex-1.0.18.jar:na]
	at org.jbibtex.BibTeXParser.Database(BibTeXParser.java:246) ~[jbibtex-1.0.18.jar:na]
	at org.jbibtex.BibTeXParser.parse(BibTeXParser.java:57) ~[jbibtex-1.0.18.jar:na]
....

I will be parsed in when i use 'parseFully' but it does skip the Entry. But i need it :/

Please help or any suggestions

**Comment by vruusmann** [comment]
> @book{.,}

You have a BibTeX entry there, whose identifier is a sole dot (`.`) character. I'm not sure if that's valid.

You can tweak the identifier "formula" here:
https://github.com/jbibtex/jbibtex/blob/master/src/main/javacc/bibtex.jj#L345-L361

Specifically, you should add the dot character into the list of valid name start symbols:
https://github.com/jbibtex/jbibtex/blob/master/src/main/javacc/bibtex.jj#L358

**Comment by anon753307** [comment]
Hello,

i have added the dependencie to my project, but i don't have the file bibtex.jj

Does the BibTexParser generate the bibtex.jj ?? Because I would like to add the (.) too. Or is there an another way?

Can you help please?

**Comment by vruusmann** [comment]
> i don't have the file bibtex.jj

The `bibtex.jj` is part of the codebase. 

There's a link to it in my above comment:
https://github.com/jbibtex/jbibtex/issues/24#issuecomment-873027643

> Does the BibTexParser generate the bibtex.jj ??

It's the other way around - the `BibTeXParser` class _**is generated**_ based on the `bibtex.jj` grammar file.

> Because I would like to add the (.) too.

@playmaker9511 and @anon753307 - are you two friends? It's highly unusual for two people to come and ask for the same irregular behaviour in such a short timeframe.

Maybe it's a popular functionality, and should really be enabled.

**Comment by anon753307** [comment]
Good question :D No, we are not friends. But I think we got the same assignment from our teacher at the university :) We have to read a bibtex file, but there is the (.) that can't be read.

When I add the dependency, I have the following folder structure: 

![image](https://user-images.githubusercontent.com/24452901/125604458-c3c4c3a5-504d-4604-9e97-afce57d7b04b.png)

I don't have the bibtex.jj file. I already looked in the BibTeXParser Class, but I can't really find the place, where I could add the (.). 

I already tried to clone the project and add it manually to my project. But like you said above, the bibtex.jj generates the BibTeXParser, so the class is missing. Do you have maybe a suggestion? You would help us a lot.

**Comment by vruusmann** [comment]
> I think we got the same assignment from our teacher at the university :)

OK, here's the lesson for today - sometimes it's not necessary to try to figure out everything yourself; with open-source projects, you can simply ask the owner/maintainer for help.

> I already looked in the BibTeXParser Class, but I can't really find the place, where I could add the (.).

See the commit where I fixed this issue - it was about moving one symbol into the "allowed name starting symbols" in the `bibtex.jj` grammar file.

If the teacher asks, you now know what to answer!

I'll prepare and release JBibTeX version 1.0.19 to the Maven Central repository later today. Check back tomorrow morning!

**Comment by anon753307** [comment]
I appreciate it very much, thank you :)

**Comment by vruusmann** [comment]
> I'll prepare and release JBibTeX version 1.0.19 to the Maven Central repository later today.

Did it already.

This release should become visible to the general public after the next repositories' sync, which happens regularly (in every two to three hours).
