### ISSUE TITLE
Add additional symbols for citekey - to allow parsing BibTeX which uses DOIs as citekeys

### ISSUE THREAD

**Issue by marcodyga** [jbibtex/jbibtex#27]
Recently, I have been using jbibtex for parsing BibTeX citations downloaded from journal's websites. There, the DOI is often used as the citekey. The issue is that DOIs may contain a lot of symbols, which are currently not supported by jbibtex (Examples provided below).

Looking at some of the previous issues [[1]](https://github.com/jbibtex/jbibtex/issues/24) [[2]](https://github.com/jbibtex/jbibtex/issues/7) [[3]](https://github.com/jbibtex/jbibtex/issues/25) I think this could be fixed by adding the characters into `NAME_CONTINUATION_SYMBOL` in `bibtex.jj`. In real-world examples, I have found that `<`, `>`, and `;` are used relatively frequently in DOIs, and should be added there.

However, I do not know enough about LaTeX/BibTeX to tell if this might cause other problems down the road, as I was unable to find a reference describing which characters can safely be used in the citekey of BibTeX. 

According to the [DOI specifications](https://www.doi.org/doi_handbook/2_Numbering.html), there are no restrictions on the characters used in a DOI. One might consider to include additional ASCII characters such as `"`, `#`, `$`, `%`, `&`, `=`, `@`, `\`, `^`, `{`, `|`, `}`, `~` into bibtex.jj, though it seems quite risky to add some of these.

**Examples:**

The following BibTeX code can be downloaded from Wiley Online Library from the following URL:
[https://onlinelibrary.wiley.com/action/downloadCitation?direct=direct&doi=10.1002/(SICI)1521-4133(199812)100:12<524::AID-LIPI524>3.0.CO;2-6&format=bibtex&include=abs&submit=Download](https://onlinelibrary.wiley.com/action/downloadCitation?direct=direct&doi=10.1002/(SICI)1521-4133(199812)100:12<524::AID-LIPI524>3.0.CO;2-6&format=bibtex&include=abs&submit=Download)

    @article{https://doi.org/10.1002/(SICI)1521-4133(199812)100:12<524::AID-LIPI524>3.0.CO;2-6,
    author = {Mang, Theo},
    title = {Umweltrelevante Kriterien zur Anwendung von Pflanzenölen und deren Derivaten im Schmierstoffbereich},
    journal = {Lipid / Fett},
    volume = {100},
    number = {12},
    pages = {524-527},
    doi = {https://doi.org/10.1002/(SICI)1521-4133(199812)100:12<524::AID-LIPI524>3.0.CO;2-6},
    url = {https://onlinelibrary.wiley.com/doi/abs/10.1002/%28SICI%291521-4133%28199812%29100%3A12%3C524%3A%3AAID-LIPI524%3E3.0.CO%3B2-6},
    eprint = {https://onlinelibrary.wiley.com/doi/pdf/10.1002/%28SICI%291521-4133%28199812%29100%3A12%3C524%3A%3AAID-LIPI524%3E3.0.CO%3B2-6},
    abstract = {Abstract Der Einsatz nachwachsender Rohstoffe und deren Derivate in Schmierstoffen wird durch ihre besondere Umweltverträglichkeit motiviert, wobei die Substitution von Mineralöl durch biologisch abbaubare Grundöle im Vordergrund steht. Inzwischen werden für nahezu alle Schmierstoffanwendungen umweltfreundliche, biologisch abbaubare Alternativen zu den herkömmlichen Mineralölprodukten angeboten. 1997 wurden in Deutschland ca. 40000 t biologisch schnell abbaubare Schmierstoffe abgesetzt, also etwa 4,5\% der gesamten Schmierstoffmenge. Die weitere Steigerung dieses Anteils ist Ziel verschiedener Maßnahmen von Regierungen und Behörden. Allgemein ist anerkannt, daß potentiell mehr als 90\% aller Schmierstoffe auf Basis nachwachsender Rohstoffe dargestellt werden können.},
    year = {1998}
    }

Parsing this code with jbibtex results in an error, e.g. `org.jbibtex.TokenMgrException: Lexical error at line 1, column 63.  Encountered: "<" (60), after : ""` and, when calling parseFully(), `java.lang.RuntimeException: org.jbibtex.ParseException: Reached unexpected EOF token` is observed.

Other DOIs with such characters inside are: [10.1002/1521-3773(20010917)40:18<3458::AID-ANIE3458>3.0.CO;2-0](https://doi.org/10.1002/1521-3773(20010917)40:18%3C3458::AID-ANIE3458%3E3.0.CO;2-0), [10.1002/(SICI)1521-3757(19981002)110:19<2724::AID-ANGE2724>3.0.CO;2-4](https://doi.org/10.1002/(SICI)1521-3757(19981002)110:19%3C2724::AID-ANGE2724%3E3.0.CO;2-4), [10.1002/1521-3773(20020603)41:11<1922::AID-ANIE1922>3.0.CO;2-T](https://doi.org/10.1002/1521-3773(20020603)41:11%3C1922::AID-ANIE1922%3E3.0.CO;2-T)...

**Comment by marcodyga** [comment]
You could try, but autodetecting the DOI is difficult, because every publisher exports BibTeX data in a slightly different format. For example, Wiley will use a full URL as the citekey (`https://doi.org/[DOI]`, see above), whereas ACS will use the following string as citekey: `doi:[DOI]` [(example)](https://pubs.acs.org/action/showCitFormats?doi=10.1021%2Fol1012857&include=cit&format=bibtex&direct=true&downloadFileName=ol1012857&href=/doi/10.1021/ol1012857), and the Royal Society will only use the last part of the DOI as citekey (e.g. `B916853B` for the DOI [10.1039/B916853B](https://doi.org/10.1039/B916853B)). 

DOIs may contain characters which would be problematic in URLs as well, such as `%` or whitespace, in the [specs](https://www.doi.org/doi_handbook/2_Numbering.html) at Chapter 2.5 there is a long-winded discussion about that.

To be honest, I do not have any experience actually using LaTeX, and I was unable to find any kind of list of permitted/forbidden characters for the citekey online. My suggestion would be to simply add characters which are known to be safe

As a workaround, I am currently using a regex to cut and replace the citekey, which circumvents the parsing problem in jbibtex, like this... maybe this code will be helpful for someone in the future:

	Pattern ptrn = Pattern.compile("\\s*(@[a-zA-Z]+\\{)[^,]+(,[\\s\\S]*)");
	Matcher matcher = ptrn.matcher(bibTeXString);
	if (matcher.matches()) {  // apply regex to bibtexstring
		// effectively cut out citekey and replace by "muh", using regex capturing groups
		bibTeXString = matcher.group(1) + "muh" + matcher.group(2);
	}

**Comment by vruusmann** [comment]
> For example, Wiley will use a full URL .. whereas ACS will use the following string .. and Royal Society will only use the last part

Excellent - the "DOI token" definition will contain matchers for all the above-stated prefixes. The suffix part may then be a "Name token"-like thing, with slightly expanded character ranges.

JavaCC grammar supports regular expressions, so I'll go ahead and borrow your code fragment.

Give me a day.

**Comment by marcodyga** [comment]
Awesome, thank you for the quick response!

**Comment by vruusmann** [comment]
@marcodyga Could you please verify that the current codebase addresses your use case?

Simply perform GitHub checkout, build locally with Apache Maven (`mvn clean install`) and attach the resulting `jbibtext-1.0-SNAPSHOT.jar` to your project. After this, do all your DOI-like identifiers parse natively, without any regular expression pre-processing?

Once I have your confirmation, I'll prepare and release a new JBibTeX library version.

**Comment by marcodyga** [comment]
@vruusmann Looks good, all my usecases are covered. 

I think most publishers (except for Wiley) are a bit more careful when using special characters in DOIs, even though the DOI foundation itself allows all sorts of characters. I haven't found any other special characters in the 1300 DOIs in my own database.

Thank you for your quick work :)

**Comment by vruusmann** [comment]
I have now prepared and released JBibTeX version 1.0.20.

Should become visible in the Maven Central repository in a few hours time.
