### ISSUE TITLE
BibTeXParser is missing in the code

### ISSUE THREAD

**Issue by tewaris** [jbibtex/jbibtex#29]
I cannot find the class `BibTeXParser`. This class is referenced everywhere.

**Comment by vruusmann** [comment]
Class `org.jbibtex.BibTeXParser` is **_automatically generated during the build process_** based on the BibTeX parser grammar file.

Check out the project, run the build, and see inside the `target/generated-sources/javacc` directory.

**Comment by tewaris** [comment]
Yes, I just figured out this. Yes, the build and tests are now running fine. Thank you for such a prompt response.
